services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"   # ホスト:コンテナ
    volumes:
      - ./app:/app              # ホットリロード的に編集したい場合
    # 別コマンドにしたければここで command を上書き可能
    # command: ["python", "app.py"]